document.getElementById("htmy").innerHTML =
'<div class="ui-grid-b">'
+'<div class="ui-block-a">'
+'<div class="ui-bar-x" style="background-color:green;">'
+'</div>'
+'</div>'
+'<div class="ui-block-b">'
+'<div class="ui-bar-x" style="background-color:#00ffb770;">'
+'<div id="exer">'
+'<CENTER>'
+'<div id="rum">'
+'<div id="demo">Перенесите слова на английском языке в область слов на русском языке, '
+'равных по смыслу	'
+'<a href="menu.html"  style="display:none;" id="box22" rel="external">Упражнение выполнено</br> переходи в меню</a>'
+'</div>'
+'</div>'
+'</CENTER>'
+'</div>'
+'<CENTER>'
+'<div id="prepos">'
+'<div id="div1" ><b>div1</b></div>'
+'<div id="div2"><b>div2</b></div>'
+'<div id="div3"><b>div3</b></div>'
+'<div id="div4" ><b>div1</b></div>'
+'<div id="div5"><b>div2</b></div>'
+'<div id="div6"><b>div3</b></div>'
+'<div id="div7" ><b>div1</b></div>'
+'<div id="div8"><b>div2</b></div>'
+'<div id="div9"><b>div3</b></div>'
+'<div id="div10" ><b>div1</b></div>'
+'<div id="div11"><b>div2</b></div>'
+'<div id="div12"><b>div3</b></div>'
+'</div>'
+'<div id="enlg">'
+'<div id="drag1" ><b>div1</b></div>'
+'<div id="drag2"><b>div2</b></div>'
+'<div id="drag3"><b>div3</b></div>'
+'<div id="drag4" ><b>div1</b></div>'
+'<div id="drag5"><b>div2</b></div>'
+'<div id="drag6"><b>div3</b></div>'
+'<div id="drag7" ><b>div1</b></div>'
+'<div id="drag8"><b>div2</b></div>'
+'<div id="drag9"><b>div3</b></div>'
+'<div id="drag10" ><b>div1</b></div>'
+'<div id="drag11"><b>div2</b></div>'
+'<div id="drag12"><b>div3</b></div>'
+'</div>'
+'</CENTER>'
+'</div>'
+'</div>'
+'<div class="ui-block-c">'
+'<div class="ui-bar-x" style="background-color:;"></div>'
+'</div>'
+'</div>'
;