
var arr1=[
'I', 
'The Johnson’s',  
'He', 
'I didn’t want to',
'We’ll', 
'I wanted to', 
'We', 
'He needs to', 
'I', 
'She',  
'Mary', 
'My parents are gone for a business trip,', 
'Ellie', 
'That’s how I', 
'My cat', 
'That’s a stupid story, my wife will never',  
'After losing my job, I was', 
'There will be a lot of paperwork, you’ll have to read,', 
'I dont’ know how it works but let’s', 
// 'In school, I didn’t', 
'I called you twice but couldn’t', 
'He didn’t see the truck coming when we was', 
'I am afraid, we', 
'I’m', 
'The boxer', 
'How to',  
'Fight and never', 
'The are', 
' ',
'Are you still',
'Are you expecting the prices to',
'',
'You have to', 
'Don’t worry about your haircut, it’ll',
'',
'I’m gonna',
'',
'A seven nation army couldn’t',
'',
'I won’t', 
'Guy,', 
'I am', 
'We are', 
'Can you', 
'I don’t know this word,',
'',
'I had to', 
'We', 
'The Patterson’s have', 
'I want to change my job, I need to', 
'My grandfather', 
'We', 
'Your effort will', 
'Don’t worry, just', 
'After', 
'Can you', 
'He', 
'Can I', 
'The car', 
'They needed a volunteer and I', 
'It has to', 
'You can’t lose weight if you don’t', 
'I’d like to', 
'',
'The plane', 
'I', 
'The boy', 
'This hat looks great,', 
'',
'This is my niece singing,', 
'Even if hear something creepy, don’t', 
'Harry stared at her and she', 
'Don’t forget to', 
'Her husband',  
'In that fairy tale, a boy could', 
'Have you', 
'Alicia Vikander', 
'Is your phone', 
'In horror movies people don’t', 
'I don’t know who that person is but we’ll', 
'Dear Santa, I’m',  
'Jack,',
'Jack,',
'How did you', 
'Where do we', 
'He wanted to', 
'They',
'Jack doesn’t', 
'I’m not in the mood to', 
'Viktoria is', 
// 'Don’t worry, I’ll', 
'Please,',
'She'
];
var arr2=[
'поспрашивал',
'отсутствовала',
'привел с собой', 
'поднять тему',
'перезвоним вам',
'навестить',
'поселимся',
'согласовать',
'наткнулся',
'подошла',
'придумала',
'приходи',
'переоделась',
'оказался',
'упал',
'не поверит',
'был сам не свой', 
'заполнить',
'выяснить',
// 'не ладил',
'дозвониться',
'садился в',
'сели',
'выхожу',
'поднялся',
'избежать наказания',
'не сдавайся',
'раздают',
'Верни это',
'встречаешься',
'упадут',
'раздайте',
'сдать', 
'отрастут',
'Держитесь!',
'проводить время',
'Подожди',
'сдержать меня',
'Продолжайте', 
'подведу тебя',
'впустите меня',
'ищу',
'нетерпением ждем', 
'присмотри', 
'найди это',
'Берегись!',
'выдумал',
'переехали',
'съехали',
'двигаться дальше',
'покинул нас',
'проезжали мимо', 
'окупятся',
'подыгрывай',
'занимался',
'устроить',
'заявился',
'переночевать',
'снизила скорость',
'согласился',
'отличаться',
'придерживаться',
'забрать обратно', 
'снимайте обувь',
'взлетел',
'перепутал с его',
'разобрал',
'примерь это',
'включи',
'сделай погромче/потише',
'не оборачивайся',
'отвернулась',
'сдать',
'оказался',
'превращаться',
'истратил',
'тренировалась',
'включен/выключен',
'убегают',
'выясним это',
'жду с нетерпением',
'успокойся',
'садись',
'сел',
'выходим',
'пригласить ее',
'расстались',
'ладит с',
'куда-то идти', 
'встречается',
// 'присмотрю',
'продолжайте',
'в итоге'

];
var arr3=[
'but nobody knew how to find that hotel',
'all last week to Mexico',
'his son to the football match',
'business at lunch',
'',
'on my way home',
'on Saturday',
'his wife to make sure they don’t have other plans',
'my ex-wife in the grocery store',
'me and asked if I was lost',
'her brilliant plan',
'',
'a witch for Halloween',
'in this small town',
'from the balcony, but it’s ok',
'it',
'',
', sign hundreds of documents',
'',
// 'my classmates',
'',
'his car',
'the wrong train',
'here, see you later!',
'and continued to fight',
'with murder',
'',
'some unsold stuff',
'',
'with Bob?',
'?',
'the invitations to everyone',
'your essay by Monday',
'',
'there!',
'with my friends today',
', I forgot my phone',
'',
'stirring until it boils',
'',
', it’s cold out there!',
'a post office',
'your next visit',
'my stuff, please?',
'in the dictionary',
'Someone’s coming!',
'a story about why I was late',
'yesterday and know no one here',
'',
'',
'when I was ten',
'the City Hall, when Ann saw Harry in the street',
'',
', ok?',
'all day, James is too tired to play with his kids',
'a meeting with him?',
'in the middle of the night',
'at my friend’s house?',
'passing us by',
'',
'',
'the diet',
'the bike',
'your shoes and come in',
'',
'your brother',
'his toy',
'',
'the TV',
'!', 
'',
'',
'your homework tomorrow',
'to be a serial killer',
'a wolf',
'all the painkillers?',
'six days a week for her Lara Croft role',
'now?',
'',
'',
'to your visit',
', it’s just a joke',
'the car',
'the plane without a ticket?',
'?',
'',
'soon after their engagement',
'his sister',
'tonight',
'that creepy guy',
// 'your bag',
', that’s a very interesting story',
'working as a teacher'
];
var arr4=[
'asked around',
'were away',
'brought along', 
'bring up',
'call you back',
'call by', 
'checked in', 
'check with', 
'came across', 
'came up to',
'came up with', 
'come over',
'dressed up as',
'ended up',
'fell down', 
'fall for',
'falling apart',
'fill in',
'figure it out',
// 'get along with', 
'get through',
'getting in', 
'got on', 
'getting off', 
'got up', 
'get away',
'give up',
'giving away', 
'Give it back!', 
'going out',
'go down',
'Hand out', 
'hand in', 
'grow back',
'Hang in', 
'hang out', 
'Hold on',
'hold me back',
'Keep on',
'let you down',
'let me in',
'looking for', 
'looking forwad to', 
'look after', 
'look it up', 
'Look out!', 
'make up', 
'moved in', 
'moved away',
'move on',
'passed away', 
'were passing by', 
'pay off',
'play along',
'running around', 
'set up', 
'showed up', 
'sleep over', 
'slowed down', 
'signed up',
'stand out',
'stick to', 
'take back', 
'Take off', 
'took off', 
'took him for', 
'took apart', 
'try it on',
'Turn on', 
'turn it up/down', 
'turn around',
'turned away',
'turn in', 
'turned out',
'turn into', 
'used up', 
'worked out', 
'on/off', 
'run away', 
'figure it out',
'looking forward',
'calm down',
'get in', 
'get on', 
'get off',
'ask her out',
'broke up', 
'get along with', 
'go out', 
'going out with', 
// 'look after', 
'go on',
'ended up'

];











