var arr1=[
'cyclical',
'reflecting about one-third of the total amount of sunlight',
'recycle', 
'soil',
'precipitation', 
'hydropower',
'green energy',
'wind turbines',
'solar panels',
'electric car',
'climate warming',
'effects on the environment',
'effects that scientists had predicted',
'accelerated sea level rise',
'due to greenhouse gases produced by human activities',
'Solar Irradiance',
'greenhouse gas emissions',
'carbon dioxide (CO2)',
'methane (CH4)',
'nitrous oxide (N2O) ',
'concentrations of greenhouse gases',
'carbon dioxide from the atmosphere',
'greening of the forests',
'ice melts',
'absorbs heat',
'makes the Earth warmer overall',
'may divert the Gulf Stream',
'rapid release of methane',
'lie beneath permafrost in Arctic regions',
'permafrost thaws',
'clean energy',
'Paris climate agreement',
'сan forestall a climate catastrophe',
'environmentally sensitive way', 
'mine nickel efficiently', 
'made up to attract',
'mining company', 
'prospect of working',
'outnumber', 
'Environmental Defense Fund',
'promising places',
'is ramping up production',
'under construction',
'they are increasing production capacity',
'that may not sound like a lot'
];
var arr2=[
'циклический',
'отражая около трети от общего количества солнечного света',
'перерабатывать',
'почва', 
'осадки', 
'гидроэнергетика', 
'зеленая энергетика',
'ветряные турбины',
'солнечные батареи',
'электромобиль',
'потепление климата',
'воздействие на окружающую среду',
'эффекты, которые предсказывали ученые',
'ускоренное повышение уровня моря',
'из-за парниковых газов, производимых в результате деятельности человека',
'Солнечное излучение',
'выбросы парниковых газов',
'углекислый газ (CO2)',
'метан (CH4)',
'оксид азота',
'концентрации парниковых газов',
'углекислый газ из атмосферы',
'озеленение лесов',
'лед тает',
'поглащает тепло',
'делает Землю теплее в целом',
'может отклонить Гольфстрим',
'быстрое выделение метана',
'лежат под вечной мерзлотой в арктических регионах',
'вечная мерзлота тает',
'чистая энергия',
'Парижское соглашение по климату',
'может предотвратить климатическую катастрофу',
'экологически чистый способ', 
'добывать никель эффективно',
'создан для привлечения', 
'добывающая компания', 
'перспектива работы', 
'превосходить численностью', 
'Фонд защиты окружающей среды',
'перспективные места',
'наращивает производство',
'в разработке',
'они наращивают производственные мощности',
'это может показаться не очень много'

];

