var arr1=[
'assets/resources',
'application form',
'former',
'learning agility (fast learner)',
'quick learner(enjoy learning new things)',
'eventually',
'the course of a persons career',
'design looks crisp, sharp and clear',
'external Style Sheet',
'excites',
'embedded Style Sheet',
'verbs',
'in depth knowledge of...',
'in-depth understanding of...',
'open to change',
'pretty substantial audience',
'pick up',
'fill out',
'applicant',
'planning skills',
'communication skills',
'interpersonal skills',
'self motivated and determined',
'Intelligence and self confidence',
'exceptions',
'team player who shares knowledge and ideas with colleagues',
'adapt well to new situations',
'measure',
'could master one technology this year',
'have a stable work history',
'to hire someone',
'to recruit employee',
'to teach them how to do the job',
'beginner',
'found the prospect of working', 
'lacking some skills',
'recent issues',
'disagreement',
'lower position',
'need to apply and submit',
'have possess proactive approach',
'train person',
'explain',
'clause',
'he will be put in that position',
'describe your workflow',
'determine',
'optimistic',
'quality oriented',
'Success oriented and natural leader',
'implement',
'shortlist',
'shortlisting',
'answer',
'well-developed skills in...',
'relative, fixed, absolute',
'statically positioned element',
'display property',
'render',
'negotiate',
'retrain',
'promising places',
'the pros and cons',
'increase performance',
'applying for a job',
'maintaining',
'share',
'emphasise',
'purchase',
'demoted',
'suppose',
'preferred development environment',
'to submit resume',
'advantages/disadvantages',
'terminated internship',
'pursue',
'job applicant',
'exaggerating',
'application',
'to promote',
'rebound occurs', 
'prototypal inheritance works',
'pseudo-elements',
'versatile',
'layout',
'CV is curriculum vitae',
'easily solve technical problems',
'with broad experience in...',
'fluently read and write in English',
're',
'control systems',
'keep abreast of new software applications',
'keep alert to new computer hardware',
'employee',
'advice',
'slashed staff', 
'make it three or five',
'collaborator',
'able to keep deadlines successfully',
'able to work independently',
'able to prioritize',
'multitasking',
'ability to talk and conduct business in 2 languages',
'average written and verbal communication skills',
'intermediate',
'trying to learn from past mistakes',
'existing CSS frameworks',
'stylesheets',
'patient',
'hardworking',
'laid off have retired', 
'speaking in public',
'well organized',
'regards to front-end security',
'fonts',
'expert',
'What are your weaknesses?',
'You can start telling about yourself',
'Do you think you’re qualified for this position?',
'Do you think your experience matches the needs of the job?',
'How could you benefit our team?',
'What are your strengths?',
'What were your duties and responsibilities in your previous job?',
'How does your experience prepare you for this role?',
'candidate',
'What are your salary expectations?',
'Why do you want this job?',
'Why should we hire you?',
'Why are you looking for a new position now?',
'Why are you leaving your job?',
'Why did you leave Position X?',
'Tell me about an accomplishments',
'Tell me more about yourself',
'Could you please tell me about your job experience?',
'Do you have any questions?',
'What can you tell me about yourself?',
'What should we know about you?',
'sophisticated',
'acquainted',
'interaction',
'approve yourself',
'implementation',
'a professional who owns technology',
'to influence the development',
'sharing the corporate spirit and values',
'to merger talks with a rival',
'tool which spawns a web server',
'executes source code',
'developer',
'tests passed or failed',
'manually',
'it triggers the test run by sending a signal',
'brief overview',
'outline of workflow',
'roughly',
'reconnect immediately',
'instructs the client',
 'the onload event handler connects the context page',
 're-dispatches',
 'achievements'

];
var arr2=[
'активы /ресурсы',
'анкета поступающего на работу',
'прежний, составитель',
'быстрая обучаемость',
'быстро обучаемый (люблю изучать новое)',
'в конце концов',
'в рамка карьеры человека',
'ваш дизайн выглядит четким, резким и ясным',
'внешняя таблица стилей',
'волнует',
'встроенная таблица стилей',
'глаголы',
'глубокие познания в...',
'глубокое понимание...',
'готов меняться',
'довольно солидная аудитория',
'забрать',
'заполнить',
'заявитель',
'навыки планирования',
'коммуникативные навыки',
'коммуникативные навыки',
'инициативный и целеустремленный',
'интеллект и уверенность в себе',
'исключения',
'командный игрок, делюсь знаниями и идеями с коллегами',
'легко адаптируюсь к новым ситуациям',
'мера',
'мог бы освоить одну технологию в этом году',
'моя профессиональная биография отличается стабильностью',
'нанять кого-нибудь',
'нанять на работу сотрудника',
'научить как делать работу',
'начинающий',
'нашел перспективу работы', 
'не хватает некоторых навыков',
'недавние проблемы',
'несогласие',
'низкая должность',
'нужно применить и подать заявку',
'обладаю активной жизненной позицией, инициативен',
'обучать человека',
'объяснять',
'оговорка, пункт, параграф',
'он займет эту должность',
'опишите свой рабочий процесс',
'определять',
'оптимистичен',
'ориентирован на качество',
'ориентирован на успех, прирожденный лидер',
'осуществлять',
'отбирают',
'отбор',
'ответ',
'отлично развитые навыки в ...',
'относительный, фиксированный, абсолютный',
'статически позиционированный элемент',
'отображать свойство',
'отображать',
'переговоры',
'переквалифицироваться',
'перспективные места',
'плюсы и минусы/за и против',
'повысить производительность',
'подать заявку на работу',
'поддержание',
'поделиться',
'подчеркните',
'покупка',
'понижен',
'предположим',
'предпочтительная среда разработки',
'представить резюме',
'преимущества/недостатки',
'прекращенная стажировка', 
'преследовать',
'претендент на работу',
'преувеличивая',
'применение, заявление',
'продвигать, получить высокую должность, повышение зар.пл.',
'происходит отскок',
'прототипное наследование',
'псевдо-элементы',
'разносторонен, универсален',
'расположение, макет',
'Резюме - автобиография',
'с легкостью решаю технические проблемы',
'с обширным опытом в...',
'свободно пишу и читаю на английском',
'сделать что-то снова',
'системы управления',
'слежу за выходом новых компьютерных приложений',
'слежу за новинками в области компьютерного оборудования',
'служащий, работник',
'совет',
'сократили персонал',
'составляют три или пять',
'сотрудник /коллега',
'способен выполнять работу в срок',
'способен работать независимо',
'способен расставлять приоритеты',
'способен успешно работать с несколькими проектами',
'способность разговаривать и вести дела на двух языках',
'средние навыки письменного и устного общения',
'средний уровень',
'стараюсь учиться на прошлых ошибках',
'существующие CSS-фреймворки',
'таблицы стилей',
'терпелив',
'трудолюбивый, работоспособный',
'уволены вышли на пенсию', 
'умение выступать перед аудиторией',
'хорошо организован',
'что касается безопасности внешнего интерфейса',
'шрифт',
'эксперт',
'А какие у вас слабости?', 
'Вы можете начать свой рассказ о себе.',
'Вы считаете, что вы подходите для данной позиции?',
'Как вы думаете, вашего опыта работы достаточно для этой позиции?',
'Как вы можете принести пользу нашей команде?',
'Какие ваши сильные стороны?',
'Какие обязанности были у вас на предыдущей работе?',
'Каким образом ваш опыт работы подготовил вас к данной позиции?',
'кандидат',
'На какую зарплату вы рассчитываете?',
'Почему вам интересна эта работа?',
'Почему мы должны вас нанять?',
'Почему вы ищете новую работу?',
'Почему вы уходите с предыдущего места работы?',
'Почему вы ушли с работы … ?',
'Расскажи мне о своих достижениях',
'Расскажите о себе',
'Расскажите, пожалуйста, о вашем опыте работы',
'У вас остались вопросы ко мне?',
'Что вы можете рассказать о себе?',
'Что нам следует знать о вас?',
'сложный',
'знакомый',
'взаимодействие',
'проявить себя',
'реализация',
'профессионал, владеющий технологиями',
'влиять на развитие',
'разделяя корпоративный дух и ценности',
'говорить о слиянии с конкурентом',
'инструмент, который запускает веб-сервер',
'выполняет исходный код',
'разработчик',
'тесты пройдены или не пройдены',
'вручную',
'запускает тестовый прогон, посылая сигнал',
'краткий обзор',
'схема рабочего процесса',
'примерно',
'переподключиться немедленно',
'поручает клиенту',
'обработчик событий загрузки соединяет контекстную страницу',
'переадресации',
'достижения'

];