var arr4=[
'assets/resources',
'application form',
'former',
'learning agility',
'quick learner',
'eventually',
'in depth knowledge of...',
'in-depth understanding of...',
'open to change',
'fill out',
'applicant',
'planning skills',
'communication skills',
'interpersonal skills',
'self motivated and determined',
'intelligence',
'confidence',
'team player',
'adapt well to new situations',
'to hire someone',
'to recruit employee',
'to teach them how to do the job',
'beginner',
'lacking some skills',
'lower position',
'need to apply and submit',
'have possess proactive approach',
'train person',
'explain',
'clause',
'he will be put in that position',
'describe your workflow',
'determine',
'optimistic',
'quality oriented',
'success oriented and natural leader',
'implement',
'shortlist',
'shortlisting',
'answer',
'well-developed skills in...',
'relative, fixed, absolute',
'statically positioned element',
'display property',
'render',
'negotiate',
'retrain',
'promising places',
'the pros and cons',
'increase performance',
'applying for a job',
'maintaining',
'share',
'emphasise',
'preferred development environment',
'to submit resume',
'advantages/disadvantages',
'terminated internship',
'pursue',
'job applicant',
'exaggerating',
'application',
'to promote',
'prototypal inheritance works',
'pseudo-elements',
'versatile',
'layout',
'CV is curriculum vitae',
'easily solve technical problems',
'with broad experience in...',
'fluently read and write in English',
're',
'control systems',
'employee',
'advice',
'slashed staff', 
'make it three or five',
'collaborator',
'able to keep deadlines successfully',
'able to work independently',
'able to prioritize',
'multitasking',
'ability to talk and conduct business in 2 languages',
'average written and verbal communication skills',
'intermediate',
'trying to learn from past mistakes',
'patient',
'hardworking',
'laid off have retired', 
'speaking in public',
'well organized',
'regards to front-end security',
'fonts',
'expert',
'sophisticated',
'acquainted',
'interaction',
'approve yourself',
'implementation',
'to influence the development',
'sharing the corporate spirit and values',
'developer',
'tests passed or failed',
'manually',
'brief overview',
'outline of workflow',
'roughly',
'reconnect immediately',
 're-dispatches'


];
var arr2=[
'активы /ресурсы',
'анкета поступающего на работу',
'предыдущий, составитель',
'быстрая обучаемость',
'быстро обучаемый',
'в конце концов',
'глубокие познания в...',
'глубокое понимание...',
'готов меняться',
'заполнить',
'заявитель',
'навыки планирования',
'коммуникативные навыки',
'коммуникативные навыки',
'инициативный и целеустремленный',
'интеллект',
'уверенность в себе',
'командный игрок',
'легко адаптируюсь к новым ситуациям',
'нанять кого-нибудь',
'нанять на работу сотрудника',
'научить как делать работу',
'начинающий',
'не хватает некоторых навыков',
'низкая должность',
'нужно применить и подать заявку',
'обладаю активной жизненной позицией, инициативен',
'обучать человека',
'объяснять',
'оговорка, пункт, параграф',
'он займет эту должность',
'опишите свой рабочий процесс',
'определять',
'оптимистичен',
'ориентирован на качество',
'ориентирован на успех, прирожденный лидер',
'осуществлять',
'отбирают',
'отбор',
'ответ',
'отлично развитые навыки в ...',
'относительный, фиксированный, абсолютный',
'статически позиционированный элемент',
'отображать свойство',
'отображать',
'переговоры',
'переквалифицироваться',
'перспективные места',
'плюсы и минусы/за и против',
'повысить производительность',
'подать заявку на работу',
'поддержание',
'поделиться',
'подчеркните',
'предпочтительная среда разработки',
'представить резюме',
'преимущества/недостатки',
'прекращенная стажировка', 
'преследовать',
'претендент на работу',
'преувеличивая',
'применение, заявление',
'продвигать, получить высокую должность, повышение зар.пл.',
'прототипное наследование',
'псевдо-элементы',
'разносторонен, универсален',
'расположение, макет',
'Резюме - автобиография',
'с легкостью решаю технические проблемы',
'с обширным опытом в...',
'свободно пишу и читаю на английском',
'сделать что-то снова',
'системы управления',
'служащий, работник',
'совет',
'сократили персонал',
'составляют три или пять',
'сотрудник /коллега',
'способен выполнять работу в срок',
'способен работать независимо',
'способен расставлять приоритеты',
'способен успешно работать с несколькими проектами',
'способность разговаривать и вести дела на двух языках',
'средние навыки письменного и устного общения',
'средний уровень',
'стараюсь учиться на прошлых ошибках',
'терпелив',
'трудолюбивый, работоспособный',
'уволены вышли на пенсию', 
'умение выступать перед аудиторией',
'хорошо организован',
'что касается безопасности внешнего интерфейса',
'шрифт',
'эксперт',
'сложный',
'знакомый',
'взаимодействие',
'проявить себя',
'реализация',
'влиять на развитие',
'разделяя корпоративный дух и ценности',
'разработчик',
'тесты пройдены или не пройдены',
'вручную',
'краткий обзор',
'схема рабочего процесса',
'примерно',
'переподключиться немедленно',
'переадресации'


];
arr1=[ " ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" "

];
arr3=[" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" "
];