var arr1=[
'involved',
 'considering',
 'perception', 
 'suppose',
 'complain',
 'constantly',
'compassionate',
'exquisite',
 'coincide',
 'subtle',
 'long-term',
 'couple',
 'decade',
 'annual',
 'ripe',
 'caution',
'override',
 'generally',
 'delay',
 'delayed',
 'originally',
'blame',
 'revealing', 
 'revealed', 
 'modest',
 'thrusters',
 'eliminated', 
'slump', 
'dropped',
 'sobering', 
 'livelihoods', 
 'shortage', 
'outnumber', 
'misaligned',
 'inevitable',
 'disappointment', 
 'unreliable',
 'acceleration',
 'pledge',
 'strive',
 'accelerate',
 'hesitation', 
 'fight/battle', 
 'importance', 
 'disagreements', 
 'challenge',
 'resolution', 
 'split',
 'evolving/developing',
 'struck out',
 'fascinate', 
 'tempting', 
 'peacefully', 
 'violence',
 'far from peaceful',
 'rivalled',
 'Neanderthals', 
 'atop the food chain',
 'rival', 
 'strikingly', 
 'implies',
 'common',
 'inherited', 
 'intrinsic', 
 'ancient', 
 'reveals', 
 'remarkably',
 'shrines',
 'defies',
 'hesitated',
 'juxtapose',
 'compare',
'one rainy afternoon',
'a small country hotel',
'the newcomer was s short stout man',
'noticing that some of the guests had formed a group around a large advertisement',
'mr took out his glasses',
'ran away',
'six feet in height',
'speaks handsomely ',
'reliable proof',
'said aloud',
'said another man in the group',
'makes money out of it',
'interrupted by the arrival of a well-dressed gentleman',
'expressive blue eyes',
'turned with an indifferent air',
'he read it through',
'newcomer',
'it seemed to him he had met the man somewhere',
'I hardly recognized you',
'I see you remember me',
'when they  entered the room upstairs',
'looked mr straight in the face',
'I am fairly well disguised, it seems',
'I have dyed my hair black',
'could not say a word',
'my duty to tell you so',
'awful risk',
'coming up, sitting down in front of him',
'you are changed beyond recognition'
];
var arr2=[
'вовлеченный',
'учитывая',
'восприятие',
'предполагать', 
'жаловаться',
'постоянно',
'состродательный',
'изысканный',
'совпадать',
 'тонкий', 
 'долгосрочный', 
 'пара', 
 'десятилетие', 
 'годовой',
 'зрелый, спелый',
 'осторожность',
'отменять', 
'в целом, обычно',
 'задержка', 
 'отложенный', 
 'первоначально',
'вина', 
 'выявление', 
'выявленный', 
'скромный', 
'двигатели', 
'устранен', 
'спад',
 'упал', 
 'отрезвляющий',
 'средства к существованию',
 'нехватка', 
'превосходить численностью', 
'разрегулированный', 
'неизбежный', 
'разочарование',
 'ненадежна', 
 'ускорение',
'залог', 
'бороться', 
'ускорять', 
'нерешительность', 
'борьба',
 'важность', 
 'разногласия', 
 'проблема', 
'разрешение', 
'раскол',
 'развивающийся', 
 'направляться,</br>вычеркнуть', 
 'очаровывать', 
 'заманчивый', 
 'мирно', 
 'жестокость',
'далеко не мирный',
 'соперничал', 
 'Неандертальцы', 
 'на вершине пищевой </br>цепи', 
 'соперник',
 'поразительно', 
 'подразумевает',
'общий,</br>распространенный', 
'унаследованный', 
'собственный',
 'древний',
 'раскрывать', 
 'необыкновенно', 
 'святыни',
'бросает вызов',
 'колебался',
'сопоставить',
'сравнить',
'один дождливый день',
'небольшой загородный отель',
'новоприбывший оказался невысоким толстяком',
'заметив, что некоторые из гостей образовали группу вокруг большой рекламы',
'мистер достал очки',
'сбежал',
'шесть футов в высоту',
'говорит красиво',
'надежное доказательство',
'сказал вслух',
'сказал другой человек в группе',
'зарабатывает на этом деньги',
'прервало появление хорошо одетого джентльмена',
'выразительные голубые глаза',
'повернулся с безразличным видом',
'он прочел ее до конца',
'новоприбывший',
'ему показалось, что он где-то встречал этого человека',
'Я едва узнал тебя',
'Я вижу ты помнишь меня',
'когда они вошли в комнату наверху',
'посмотрел мистеру прямо в лицо',
'похоже, я довольно хорошо замаскировался',
'Я покрасила волосы в черный цвет',
'не мог сказать ни слова',
'мой долг сказать вам об этом',
'ужасный риск',
'подошедший, садится перед ним',
'вы изменились до неузнаваемости'
];
