var arr1=[
"blow up",
"give up",
"hand in",
"look forward to",
"make up",
"pull out",
"put out",
"speed up",
"find out",
"go against",
"leave out",
"look up to",
"point out",
"put off",
"put together",
"stand up for",
"get off",

];
var arr2=[
"explode",
"surrender",
"submit",
"anticipate",
"fabricate",
"extract",
"extinguish",
"accelerate",
"ascertain",
"oppose",
"omit",
"admire, respect",
"indicate",
"postpone",
"assemble, compose",
"defend",
"depart",

];
var arr3=[
"взрывать(ся)",
"сдаваться",
"подавать (документы)",
"ожидать",
"выдумывать",
"извлекать, вытаскивать",
"гасить (огонь)",
"ускорять(ся)",
"уточнять, выяснять",
"возражать, противодействовать",
"упускать (не замечать)",
"восхищаться, уважать",
"показывать",
"откладывать (на потом)",
"собирать",
"защищать",
"отправляться",

];