arr1=[
'Solar System',
'planet',
'Universe',
'Galaxy',
'black hole',
'star',
'Milky Way',
'space/cosmos',
'astronaut',
'oxygen',
'asteroid',
'gravity',
'scientists',
'Sun',
'Earth',
'meteorites',
'aerospace agency NASA',
'rocket',
'astronaut',
'Luna',
'cosmic radiation',
'gravitational pull',
'light speed',
'quanta ',
'event horizon',
'piece of light',
'constellations',
'terrestrial',
'interstellar',
'comet',
'satellite',
'planetary conjunction',
'the day of the solstice',
'Jupiter and Saturn align in the night sky',
'The planets have been moving closer together each night',
'reached their closest point on 21 December',
'have been keeping a close eye on the weather',
'Given a gap in the winter gloom',
'both planets would have appeared in the southwest sky',
'just above the horizon, shortly after sunset',
'the conjunction of Jupiter and Saturn',
'have not been this close to each other in a dark sky for 800 years'

];

arr2=[
'Солнечная система',
'планета',
'Вселенная ',
'Галактика',
'черная дыра',
'звезда',
'Млечный путь',
'космос',
'космонавт',
'кислород',
'астероид',
'гравитация',
'ученые',
'Солнце',
'Земля',
'метеориты',
'аэрокосмическое агентство NASA',
'ракета',
'астронавт',
'Луна',
'космическая радиация',
'гравитационное притяжение',
'скорость света',
'кванты ',
'горизонт событий',
'частица света',
'созвездия',
'земной',
'межзвездный',
'комета',
'спутник',
'планетарное соединение',
'день солнцестояния',
'Юпитер и Сатурн выравниваются в ночном небе',
'Планеты сближались каждую ночь',
'достигли своего максимального сближения 21 декабря',
'внимательно следили за погодой',
'Учитывая пробел в зимнем мраке',
'обе планеты появились бы в юго-западном небе',
'чуть выше горизонта, вскоре после захода солнца',
'соединение Юпитера и Сатурна',
'не были так близко друг к другу в темном небе 800 лет'



];
